// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvyuchjyeszrrmcsdren.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2eXVjaGp5ZXN6cnJtY3NkcmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTAxMjEsImV4cCI6MjA3Mzc4NjEyMX0.itYNtGx8UoAr4-wriYLCvIdlVtbrnPoFAmyMz4kNyTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});